version: "3.9"
services:
  #PHP Service
  ngo_frontend:
    build:
      args:
        user: ahrasel
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: ngo_frontend
    container_name: ngo_frontend
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ngo_frontend_network

  #MySQL Service
  ngo_frontend_db:
    image: mysql:8.0
    container_name: ngo_frontend_db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ngo_frontend_mysql_data:/var/lib/mysql
    networks:
      - ngo_frontend_network

  #Nginx Service
  ngo_frontend_nginx:
    image: nginx:alpine
    container_name: ngo_frontend_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ngo_frontend_network
  # phpmyadmin service
  ngo_frontend_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: ngo_frontend_phpmyadmin
    depends_on:
      - ngo_frontend_db
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ngo_frontend_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 50M
    networks:
      - ngo_frontend_network

  ngo_frontend_redis_cache:
    image: redis:alpine
    restart: always
    container_name: ngo_frontend_redis_cache
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - ngo_frontend_cache:/data
    networks:
    - ngo_frontend_network

#Docker Networks
networks:
  ngo_frontend_network:
    driver: bridge

#Volumes
volumes:
  ngo_frontend_mysql_data:
  ngo_frontend_cache:
